repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        files: ^python/mary_elizabeth_utils/
        additional_dependencies:
          [
            types-PyYAML,
            types-colorama,
            types-tqdm,
            polars,
            matplotlib,
            seaborn,
            pandas,
            numpy,
            pydantic,
          ]
        exclude: ^python/mary_elizabeth_utils/(mwx|profile_data)\.py$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
