# Base directory for the project
base_dir: "/path/to/base/directory"

# Directory for output files
output_dir: "/path/to/output/directory"

# Year range for data processing
start_year: 2000
end_year: 2022

# Register configurations
registers:
  # LMDB:
  #   file_pattern: "lmdb_{year}.parquet"
  #   location: "/path/to/lmdb/data"
  # LPR_ADM:
  #   file_pattern: "lpr_adm_{year}.parquet"
  #   location: "/path/to/lpr_adm/data"
  LPR_DIAG:
    file_pattern: "lpr_diag_{year}.parquet"
    location: "/path/to/lpr_diag/data"
  # LPR_SKSOPR:
  #   file_pattern: "lpr_sksopr_{year}.parquet"
  #   location: "/path/to/lpr_sksopr/data"
  MFR:
    file_pattern: "mfr_{year}.parquet"
    location: "/path/to/mfr/data"
  # PSYK_ADM:
  #   file_pattern: "psyk_adm_{year}.parquet"
  #   location: "/path/to/psyk_adm/data"
  # PSYK_DIAG:
  #   file_pattern: "psyk_diag_{year}.parquet"
  #   location: "/path/to/psyk_diag/data"
  # SSSY:
  #   file_pattern: "sssy_{year}.parquet"
  #   location: "/path/to/sssy/data"
  AKM:
    file_pattern: "akm_{year}.parquet"
    location: "/path/to/akm/data"
  FAIK:
    file_pattern: "faik_{year}.parquet"
    location: "/path/to/faik/data"
  # IDAN:
  #   file_pattern: "idan_{year}.parquet"
  #   location: "/path/to/idan/data"
  # ILME:
  #   file_pattern: "ilme_{year}.parquet"
  #   location: "/path/to/ilme/data"
  IND:
    file_pattern: "ind_{year}.parquet"
    location: "/path/to/ind/data"
  BEF:
    file_pattern: "bef_{year}.parquet"
    location: "/path/to/bef/data"
  # DOD:
  #   file_pattern: "dod_{year}.parquet"
  #   location: "/path/to/dod/data"
  # DODSAARS:
  #   file_pattern: "dodsaars_{year}.parquet"
  #   location: "/path/to/dodsaars/data"
  # FTBARN:
  #   file_pattern: "ftbarn_{year}.parquet"
  #   location: "/path/to/ftbarn/data"
  UDDF:
    file_pattern: "uddf_{year}.parquet"
    location: "/path/to/uddf/data"

# Table names
table_names:
  - Person
  - Family
  - Child
  - Diagnosis
  - Medication
  - Healthcare
  - Employment
  - Income
  - Education
  - Death
  - Birth
  - SocioEconomic
  - Psychiatric

# Path to the CSV file containing ICD-10 codes
icd10_codes_file: "data/icd10.csv"

# Numeric columns for analysis and validation
numeric_cols:
  - birth_date
  - family_size
  - total_income
  - VAEGT_BARN
  - LAENGDE_BARN
  - GESTATIONSALDER_DAGE
  - APGARSCORE_EFTER5MINUTTER
  - VMO_A_INDK_AM_BIDRAG_BETAL
  - LOENMV_13
  - PERINDKIALT_13

# Categorical columns for analysis and validation
categorical_cols:
  - gender
  - origin_type
  - family_type
  - socioeconomic_status
  - KOEN
  - IE_TYPE
  - CIVST
  - SOCSTIL_KODE
  - SAGSART
  - C_PATTYPE

# Data validation settings
validation:
  missing_value_threshold: 0.1 # Maximum allowed proportion of missing values
  outlier_detection:
    method: IQR # Interquartile Range method
    factor: 1.5 # IQR factor for outlier detection

# # Data transformation settings
# transformations:
#   age_calculation:
#     reference_date: "2023-01-01"

# # Cohort creation settings
# cohort_creation:
#   exposed_group:
#     max_age_at_diagnosis: 5 # Maximum age (in years) for diagnosis to be considered childhood onset
#   matching:
#     variables:
#       - birth_date
#       - gender
#       - municipality_code
#     caliper: 0.2 # Caliper for propensity score matching

# # Analysis settings
# analysis:
#   time_periods:
#     - name: short_term
#       duration: 1 # 1 year after diagnosis
#     - name: medium_term
#       duration: 5 # 5 years after diagnosis
#     - name: long_term
#       duration: 10 # 10 years after diagnosis
#   outcomes:
#     - name: parental_income
#       variable: total_income
#     - name: parental_employment
#       variable: socioeconomic_status

# # Reporting settings
# reporting:
#   output_format:
#     - pdf
#     - html
#   charts:
#     - bar
#     - line
#     - scatter
#   statistical_tests:
#     - t_test
#     - chi_square
#     - regression
